baseURL = 'https://jack.strain.cx/'
languageCode = 'en-gb'
title = 'Jack Strain'
theme = 'simple-style'

[params]
subtitle = 'A collection of things I found useful.'

[taxonomies]
tag = 'tags'

[menu]
[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menu.main]]
name = 'GitHub'
url = 'https://github.com/jackstrain'
weight = 20
[[menu.main]]
name = 'LinkedIn'
url = 'https://linkedin.com/in/jackstrain'
weight = 30
